# Generated by Django 2.0.6 on 2018-06-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='activeMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_adress', models.CharField(max_length=100)),
                ('ping_date', models.DateTimeField(verbose_name='ping date')),
            ],
        ),
    ]
